run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 15
    skip-tests: true
  lll:
    line-length: 130
  gofumpt:
    extra-rules: true
  gosec:
    excludes:
      - G101
      - G402
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: pascal

linters:
  enable-all: true
  disable:
    - execinquery # deprecated
    - gocyclo # duplicate of cyclop
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd
    - gomoddirectives
    - ireturn
    - nlreturn
    - nonamedreturns
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
